# Generated by Django 3.1.4 on 2021-01-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210109_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
