# Generated by Django 3.1.4 on 2020-12-12 22:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UsersTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('title', models.CharField(choices=[(users.models.AcademicTitle['lic'], 'lic.'), (users.models.AcademicTitle['inz'], 'inż.'), (users.models.AcademicTitle['mgr'], 'mgr.'), (users.models.AcademicTitle['dr'], 'dr.'), (users.models.AcademicTitle['prof'], 'prof.'), (users.models.AcademicTitle['prof_inz'], 'prof. inż.'), (users.models.AcademicTitle['mgr_inz'], 'mgr inż.'), (users.models.AcademicTitle['dr_inz'], 'dr inż.'), (users.models.AcademicTitle['dr_hab'], 'dr hab.'), (users.models.AcademicTitle['dr_hab_inz'], 'dr hab. inż.')], max_length=32, null=True)),
                ('groups', models.ManyToManyField(to='users.UsersGroups')),
                ('types', models.ManyToManyField(to='users.UsersTypes')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
