# Generated by Django 3.1.4 on 2020-12-05 18:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UsersTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('title', models.CharField(choices=[(users.models.AcademicTitle['lic'], 'lic.'), (users.models.AcademicTitle['inz'], 'inż.'), (users.models.AcademicTitle['mgr'], 'mgr.'), (users.models.AcademicTitle['dr'], 'dr.'), (users.models.AcademicTitle['prof'], 'prof.'), (users.models.AcademicTitle['prof_inz'], 'prof. inż.'), (users.models.AcademicTitle['mgr_inz'], 'mgr inż.'), (users.models.AcademicTitle['dr_inz'], 'dr inż.'), (users.models.AcademicTitle['dr_hab'], 'dr hab.'), (users.models.AcademicTitle['dr_hab_inz'], 'dr hab. inż.')], max_length=32, null=True)),
                ('password_hash', models.CharField(max_length=64)),
                ('groups', models.ManyToManyField(to='users.UsersGroups')),
                ('types', models.ManyToManyField(to='users.UsersTypes')),
            ],
        ),
    ]
