# Generated by Django 3.1.4 on 2020-12-05 17:38

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='UsersTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(users.models.UserType['STUDENT'], 'STUDENT'), (users.models.UserType['LECTURER'], 'LECTURER'), (users.models.UserType['GUEST'], 'GUEST')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('password_hash', models.CharField(max_length=64)),
                ('groups', models.ManyToManyField(to='users.UsersGroups')),
                ('types', models.ManyToManyField(to='users.UsersTypes')),
            ],
        ),
    ]
