# Generated by Django 3.1.4 on 2021-01-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201219_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='types',
        ),
        migrations.DeleteModel(
            name='UsersTypes',
        ),
    ]
