# Generated by Django 3.1.4 on 2020-12-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='lecturers',
            field=models.ManyToManyField(related_name='hosted_events', to='users.Users'),
        ),
        migrations.AddField(
            model_name='events',
            name='participants',
            field=models.ManyToManyField(related_name='events', to='users.Users'),
        ),
    ]
