# Generated by Django 3.1.4 on 2020-12-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201212_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='number_of_participants',
            field=models.IntegerField(default=0),
        ),
    ]
