# Generated by Django 3.1.4 on 2020-12-19 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_auto_20201212_1130'),
        ('events', '0005_auto_20201214_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='requirements',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requirements.requirements'),
        ),
    ]
