# Generated by Django 3.1.4 on 2021-01-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20201219_1509'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
