# Generated by Django 3.1.4 on 2021-01-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_delete_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.events'),
        ),
    ]
