# Generated by Django 3.1.4 on 2021-01-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20210125_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='is_root',
        ),
        migrations.AddField(
            model_name='events',
            name='is_cyclic',
            field=models.BooleanField(default=False),
        ),
    ]
