# Generated by Django 3.1.4 on 2021-01-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso_id', models.UUIDField()),
                ('access_token', models.CharField(max_length=32)),
            ],
        ),
    ]
